### ISSUE TITLE
4.1 Missing

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-smtnkc#11]
👋 Hi @smtnkc you are missing the Module 4.1 Assignment. Please post it here in this thread.

**Comment by smtnkc** [comment]
<img width="758" alt="Screen Shot 2020-06-25 at 01 10 41" src="https://user-images.githubusercontent.com/25348698/85632860-c5debf00-b680-11ea-8f1c-ce98c6c4a563.png">
