### ISSUE TITLE
Module 4.1 Missing

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-smtnkc#12]
👋 Hi @smtnkc you are missing the Module 4.1 Assignment. Please post it here in this thread.

**Comment by smtnkc** [comment]
<img width="758" alt="85632860-c5debf00-b680-11ea-8f1c-ce98c6c4a563" src="https://user-images.githubusercontent.com/25348698/86204509-54b37600-bb70-11ea-99fc-8ad245f2efa4.png">

**Comment by smtnkc** [comment]
Hi @arelia I have already replied this issue. It is in the closed issues. Thanks.

<img width="758" alt="85632860-c5debf00-b680-11ea-8f1c-ce98c6c4a563" src="https://user-images.githubusercontent.com/25348698/86204559-7d3b7000-bb70-11ea-99d2-5305e58040ca.png">
